#include "../include/dashboard.h"

String SendHTML()
{
    String html = "<!DOCTYPE html><html lang='pt-BR'><head>";
    html += "<meta charset='UTF-8'>";
    html += "<meta http-equiv='refresh' content='5'>"; // Atualiza a página a cada 5 segundos
    html += "<meta name='viewport' content='width=device-width, initial-scale=1.0'>";
    html += "<title>Hortinha 3.0</title>";
    html += "<style>";
    html += "* { margin: 0; padding: 0; box-sizing: border-box; }";
    html += "body { font-family: Arial, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; transition: background 1s ease; }";
    html += ".container { max-width: 1200px; margin: 0 auto; }";
    html += "h1 { color: white; text-align: center; margin-bottom: 30px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); transition: color 0.5s ease; }";
    html += ".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }";
    html += ".card { background: white; border-radius: 15px; padding: 25px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }";
    html += ".card h2 { color: #667eea; margin-bottom: 20px; border-bottom: 3px solid #667eea; padding-bottom: 10px; }";
    html += ".sensor-item { display: flex; justify-content: space-between; padding: 12px; margin: 10px 0; background: #f8f9fa; border-radius: 8px; }";
    html += ".sensor-label { font-weight: 600; color: #495057; }";
    html += ".sensor-value { font-size: 1.2em; font-weight: bold; color: #667eea; }";
    html += ".led-indicator { width: 60px; height: 60px; border-radius: 50%; margin: 20px auto; box-shadow: 0 0 20px; }";
    html += ".slider-container { margin: 20px 0; }";
    html += ".slider-container label { display: block; margin-bottom: 10px; font-weight: 600; }";
    html += "input[type='range'] { width: 100%; height: 8px; border-radius: 5px; background: #d3d3d3; }";
    html += ".slider-value { text-align: center; font-size: 1.5em; font-weight: bold; color: #667eea; margin-top: 10px; }";
    html += "button { background: #667eea; color: white; border: none; padding: 12px 30px; border-radius: 8px; font-size: 1em; cursor: pointer; width: 100%; margin-top: 10px; }";
    html += "button:hover { background: #764ba2; }";
    html += ".alert { padding: 15px; border-radius: 8px; margin: 10px 0; }";
    html += ".alert-danger { background: #f8d7da; color: #721c24; border-left: 4px solid #dc3545; }";
    html += ".alert-warning { background: #fff3cd; color: #856404; border-left: 4px solid #ffc107; }";
    html += "</style></head><body>";
    html += "<div class='container'>";
    html += "<h1> 🌱 Hortinha 3.0 </h1>";
    html += "<div id='alerts'></div>";
    html += "<div class='grid'>";
    html += "<div class='card'><h2>📊 Sensores Ambientais</h2>";
    html += "<div class='sensor-item'><span class='sensor-label'>🌡️ Temperatura</span><span class='sensor-value' id='temp'>--°C</span></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>💧 Umidade</span><span class='sensor-value' id='umid'>--%</span></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>☀️ Luminosidade</span><span class='sensor-value' id='luz'>--</span></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>👤 Presença</span><span class='sensor-value' id='pres'>--</span></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>UVC</span><span class='sensor-value' id='uvc'>--</span></div>";
    html += "</div>";
    html += "<div class='card'><h2>⚙️ Estado do Sistema</h2>";
    html += "<div style='text-align: center;'><div id='led' class='led-indicator' style='background: gray;'></div>";
    html += "<p id='ledStatus' style='font-size: 1.2em; font-weight: 600;'>Sistema Iniciando...</p></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>Modo</span><span class='sensor-value' id='modo'>--</span></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>Irrigação</span><span class='sensor-value' id='irr'>--</span></div>";
    html += "<div class='sensor-item'><span class='sensor-label'>Ângulo Servo</span><span class='sensor-value' id='angulo'>--°</span></div>";
    html += "</div>";
    html += "<div class='card'><h2>💧 Controle de Água</h2>";
    html += "<div class='sensor-item' style='margin-top: 20px;'><span class='sensor-label'>Status Água</span><span class='sensor-value' id='agua'>--</span></div>";
    html += "</div>";
    html += "<div class='card'><h2>📁 Relatórios CSV</h2>";
    html += "<div id='fileList'><p>Carregando arquivos...</p></div>";
    html += "</div>";
    html += "<div></div>";
    html += "<script>";
    html += "function baixarArquivo(nomeArquivo) {";
    html += "  window.location.href = '/baixarArquivo?File=' + encodeURIComponent(nomeArquivo);";
    html += "}";
    html += "function atualizarArquivos() {";
    html += "  fetch('/listarArquivos').then(r => r.json()).then(files => {";
    html += "    var fileList = document.getElementById('fileList');";
    html += "    if (!files || files.length === 0) { fileList.innerHTML = '<p>Nenhum arquivo disponível.</p>'; return; }";
    html += "    fileList.innerHTML = '';";
    html += "    files.forEach(function(File) {";
    html += "      fileList.innerHTML += `<div class='sensor-item'><span class='sensor-label'>${File}</span><button style='padding:8px 12px;' onclick=\"baixarArquivo('${File}')\">Baixar</button></div>`;";
    html += "    });";
    html += "  }).catch(function() {";
    html += "    document.getElementById('fileList').innerHTML = '<p>Erro ao carregar arquivos.</p>';";
    html += "  });";
    html += "}";
    html += "function atualizar() {";
    html += "  fetch('/getData').then(r => r.json()).then(d => {";
    html += "    document.getElementById('temp').textContent = d.temperatura + '°C';";
    html += "    document.getElementById('umid').textContent = d.umidade + '%';";
    html += "    document.getElementById('luz').textContent = d.luz;";
    html += "    document.getElementById('pres').textContent = d.presenca ? '✅ Detectada' : '❌ Ausente';";
    html += "    document.getElementById('uvc').textContent = d.uvcAtivo ? '🟣 Ativa' : '⚪ Inativa';";
    html += "    document.getElementById('modo').textContent = d.modoManual ? '🔧 Manual' : '🤖 Automático';";
    html += "    document.getElementById('irr').textContent = d.irrigando ? '💦 Ativa' : '⏸️ Inativa';";
    html += "    document.getElementById('angulo').textContent = d.angulo + '°';";
    html += "    var body = document.body;";
    html += "    var titulo = document.querySelector('h1');";
    html += "    if(d.modoNoturno) {";
    html += "      body.style.background = 'linear-gradient(135deg, #2c3e50 0%, #34495e 100%)';";
    html += "      titulo.innerHTML = '🌙 Hortinha 3.0 - Modo Noturno';";
    html += "      titulo.style.color = '#ecf0f1';";
    html += "    } else {";
    html += "      body.style.background = 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)';";
    html += "      titulo.innerHTML = '🌱 Hortinha 3.0 - Monitoramento';";
    html += "      titulo.style.color = 'white';";
    html += "    }";
    html += "    var led = document.getElementById('led');";
    html += "    var status = document.getElementById('ledStatus');";
    html += "    if(d.modoManual) { led.style.background = 'orange'; status.textContent = '🔧 Modo Manual'; }";
    html += "    else if(d.uvcAtivo) { led.style.background = '#7d3cff'; status.textContent = '🟣 UVC ativa'; }";
    html += "    else if(d.irrigando) { led.style.background = 'blue'; status.textContent = '💦 Irrigando (' + d.angulo + '°)'; }";
    html += "    else { led.style.background = 'green'; status.textContent = '✅ Sistema OK'; }";
    html += "    var alerts = document.getElementById('alerts');";
    html += "    alerts.innerHTML = '';";
    html += "    if(d.temperatura > 35) alerts.innerHTML += \"<div class='alert alert-warning'>🌡️ Temperatura alta!</div>\";";
    html += "    if(d.umidade < 30) alerts.innerHTML += \"<div class='alert alert-warning'>💧 Umidade baixa!</div>\";";
    html += "    if(d.alertas && d.alertas.length > 0) alerts.innerHTML += \"<div class='alert alert-warning'>🦠 \" + d.alertas + \"</div>\";";
    html += "    if(d.modoNoturno) {";
    html += "      alerts.innerHTML += \"<div class='alert' style='background:#34495e;color:#ecf0f1;border-left:4px solid #95a5a6'>🌙 Modo Noturno Ativo</div>\";";
    html += "    }";
    html += "    atualizarArquivos();";
    html += "  });";
    html += "}";
    html += "setInterval(function() { atualizar(); atualizarArquivos(); }, 2000);";
    html += "atualizar();";
    html += "atualizarArquivos();";
    html += "</script>";
    html += "</body></html>";
    return html;
}
